--when.repositories = ["~/Repos"]
--when.hostnames = ["maxcchuang.c.googlers.com"]

[user]
name = "maxcchuang"
email = "maxcchuang@google.com"

[aliases]
# If any flag-like element is provided, pass everything to `jj gerrit upload`,
# else insert `-r` before every argument to mimic the behavior of `jj piper upload`.
up = ["util", "exec", "--", "bash", "-c", """
    has_flag=false
    for arg; do
        if [[ $arg == -* ]]; then
            has_flag=true
            break
        fi
    done
    if $has_flag; then
        exec jj gerrit upload "$@"
    else
        args=()
        for arg; do
            args+=("-r" "$arg")
        done
        exec jj gerrit upload "${args[@]}"
    fi
""", ""]


[gerrit]
default-remote = "goog"
default-remote-branch = "main"

[templates]
commit_trailers = """
if(
  !trailers.contains_key("Change-Id"),
  format_gerrit_change_id_trailer(self)
)
"""
