--when.repositories = ["/google/src/cloud"]
--when.hostnames = ["maxcchuang.c.googlers.com"]

[user]
name = "maxcchuang"
email = "maxcchuang@google.com"

[aliases]
cc = ["piper", "citc"]
cw = ["piper", "citc", "workspace"]
up = ["piper", "upload"]
ux = ["piper", "upload", "--exported"]
