#:schema https://docs.jj-vcs.dev/latest/config-schema.json

--when.hostnames = ["maxcchuang.c.googlers.com"]
--when.repositories = ["/google/src/cloud"]

[aliases]
cc = ["piper", "citc"]
cw = ["piper", "citc", "workspace"]
up = ["piper", "upload"]
ux = ["piper", "upload", "--exported"]
