[general]
model = "google/gemini-3-flash-preview"
prompt_path = ["prompts", "fabric_prompts", "private_prompts"]

[general.model_aliases]
flash = "google/gemini-3-flash-preview"
gemini = "google/gemini-3.1-pro-preview"
gpt = "openai/gpt-5.4"

[[providers]]
name = "google"
api_key_cmd = "pass gemini/cli"

[[providers]]
name = "openai"
api_key_cmd = "pass openai/axon"

[[patterns]]
name = "jj_desc"
steps = [
  { command = "jj diff --git", output = "diff" },
  { command = "jj log -T builtin_log_detailed -n 5 -r ::@-", output = "commits" },
  # needs `commits` and `diff`
  { prompt = "@commit_message", output = ">desc_file" },

  { command = "echo '\n\nJJ: original description:\n'", output = ">>desc_file" },
  { command = "jj log -T description --no-graph -r @ | sed 's/^/JJ: /'", output = ">>desc_file" },

  { command = "jj describe --editor --stdin <{{ .desc_file }}", tty = true },

  { command = "cat {{ .desc_file }}" },
]

[[patterns]]
name = "git_commit"
steps = [
  { command = "git diff --staged -U30", output = "diff" },
  { command = "git log --max-count=5", output = "commits" },
  # needs `commits` and `diff`
  { prompt = "@commit_message", output = "commit_message" },

  { command = "git commit -e -m {{ .commit_message }}", tty = true },

  { command = "echo -n {{ .commit_message }}" },
]

[[patterns]]
name = "proofread"
steps = [
  { stdin = "{{ .INPUT }}", command = "cat", output = ">before_file" },
  { prompt = "@proofread", model = "flash", output = ">after_file" },

  { command = "riff --color=on {{ .before_file }} {{ .after_file }} >&2" },

  { command = "cat {{ .after_file }}" },
]

[[patterns]]
name = "code_review"
steps = [
  { prompt = "@review_code", model = "gemini", output = ">review" },
  { command = "glow --pager {{ .review }}", tty = true },

  { command = "cat {{ .review }}" },
]
