#!/usr/bin/env sh

VISIBILITY="-reader mdbgroup/eng-mirror"

# Use getopt to parse options
TEMP=$(getopt -o p --long private -n "$0" -- "$@")

if [ $? != 0 ]; then
    echo "Usage: create_personal_repo.sh [-p|--private] <repo_name>" >&2
    exit 1
fi

eval set -- "$TEMP"

while true; do
    case "$1" in
        -p|--private)
            VISIBILITY=""
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Internal error!" >&2
            exit 1
            ;;
    esac
done

NAME_OF_REPOSITORY=$1

if [ -z "$NAME_OF_REPOSITORY" ]; then
    echo "Usage: create_personal_repo.sh [-p|--private] <repo_name>" >&2
    exit 1
fi

gob-ctl create user/$USER/$NAME_OF_REPOSITORY $VISIBILITY -owner mdbuser/$USER
