#!/usr/bin/env bash

# quickly create and edit a bash script with strict mode enabled

file=$1

if [[ -z "$file" ]]; then
  echo "Usage: mkbash <script-file>"
  exit 1
fi

if ! [[ -f "$file" ]]; then
  cat <<'EOF' >"$file"
#!/usr/bin/env bash

EOF
fi

chmod u+x "$file"

exec ${EDITOR:-vim} "$file"
