#!/usr/bin/env bash

PACKAGES=()

for package in "$@"; do
  if [[ $package != *#* && $package != *:* ]]; then
    package="nixpkgs#$package"
  fi
  PACKAGES+=("$package")
done

nix shell "${PACKAGES[@]}"
