#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
if not csrutil status | grep -q 'System Integrity Protection status: enabled.'; then
  sudo yabai --load-sa
fi

# global settings
yabai -m config mouse_follows_focus off
# yabai -m config focus_follows_mouse autofocus
yabai -m config window_origin_display focused
yabai -m config window_shadow off
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.1
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.93
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config split_ratio 0.50
yabai -m config auto_balance on
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap
yabai -m config external_bar all:0:28

# general space settings
yabai -m config layout bsp
yabai -m config window_placement first_child
yabai -m config top_padding 0
yabai -m config bottom_padding 3
yabai -m config left_padding 3
yabai -m config right_padding 3
yabai -m config window_gap 3

# apps to not manage (keep floating)
yabai -m rule --add manage=off app='^Finder$'
yabai -m rule --add manage=off app='^System Settings$'
yabai -m rule --add manage=off app='^Messenger$'
yabai -m rule --add manage=off app='^Google Chat$'
yabai -m rule --add manage=off app='^LINE$'
yabai -m rule --add manage=off app='^Telegram$'
yabai -m rule --add manage=off app='^Heptabase$'
yabai -m rule --add manage=off app='^Obsidian$'
yabai -m rule --add manage=off sticky=on app='^Keymapp$'
yabai -m rule --add manage=off app='^Archive Utility$'
yabai -m rule --add manage=off app='^SpotMenu$'
yabai -m rule --add manage=off app="^Fantastical Helper$"
yabai -m rule --add manage=off app="^Python$"
yabai -m rule --add manage=off app="^python3$"
yabai -m rule --add manage=off app="^CleanShot X$"
yabai -m rule --add manage=off app="^Script Kit$"
yabai -m rule --add manage=off sticky=on app="^Notes$" title!="^Notes$"
yabai -m rule --add manage=off app='^Google Gemini$'
yabai -m rule --add manage=off app='^Duckie$'
yabai -m rule --add manage=off app='^T3 Chat$'
yabai -m rule --add manage=off app='^Things$'
yabai -m rule --add manage=off title='Google Single Sign On'
yabai -m rule --add manage=off app='^kitty$' title='^script kitty$' grid=5:3:1:1:1:2

yabai -m signal --add label='refresh sketchybar space apps 1' event='space_created' action='sketchybar --trigger space_apps_refresh'
yabai -m signal --add label='refresh sketchybar space apps 2' event='space_destroyed' action='sketchybar --trigger space_apps_refresh'
