"$schema" = 'https://starship.rs/config-schema.json'


format = "$all"

[character]
success_symbol = "[->](bold green)"
error_symbol = "[->](bold red)"
vimcmd_symbol = "[<-](bold green)"
vimcmd_replace_one_symbol = "[<-](bold purple)"
vimcmd_replace_symbol = "[<-](bold purple)"
vimcmd_visual_symbol = "[<-](bold yellow)"

[directory]
truncate_to_repo = false
style = "bold blue"
repo_root_style = "bold cyan"
repo_root_format = '[$before_root_path]($style)[\[$repo_root\]]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '

[hostname]
ssh_only = true
ssh_symbol = ""
style = "bold green"
format = '@[$ssh_symbol$hostname]($style) in '

[username]
style_user = "bold yellow"
format = '[$user]($style)'

[git_branch]
style = "green"
ignore_branches = ["main"]

[git_status]
format = '([$all_status$ahead_behind]($style))'
conflicted = "=$count "
ahead = "⇡$count "
behind = "⇣$count "
diverged = "⇡${ahead_count}⇣${behind_count}"
untracked = "[?$count](blue) "
stashed = "*$count "
modified = "[!$count](yellow) "
staged = "[++$count](green) "
renamed = "»$count "
deleted = "[✘$count](red) "
style = "green"

[docker_context]
disabled = true

[nix_shell]
disabled = false
heuristic = true

[custom.jj]
command = '''
jj log -r@ -n1 --ignore-working-copy --no-graph --color always  -T '
  separate(" ",
    bookmarks.map(|x| if(
        x.name().substr(0, 10).starts_with(x.name()),
        x.name().substr(0, 10),
        x.name().substr(0, 9) ++ "…")
      ).join(" "),
    tags.map(|x| if(
        x.name().substr(0, 10).starts_with(x.name()),
        x.name().substr(0, 10),
        x.name().substr(0, 9) ++ "…")
      ).join(" "),
    surround("\"","\"",
      if(
         description.first_line().substr(0, 24).starts_with(description.first_line()),
         description.first_line().substr(0, 24),
         description.first_line().substr(0, 23) ++ "…"
      )
    ),
    if(conflict, "conflict"),
    if(divergent, "divergent"),
    if(hidden, "hidden"),
  )
'
'''
when = "jj root"
symbol = "jj"

[custom.jjstate]
when = "jj root"
command = '''
jj log -r@ -n1 --no-graph -T "" --stat | tail -n1 | sd "(\d+) files? changed, (\d+) insertions?\(\+\), (\d+) deletions?\(-\)" ' ${1}m ${2}+ ${3}-' | sd " 0." ""
'''
