"$schema" = 'https://starship.rs/config-schema.json'


format = "$all"

[character]
success_symbol = "[->](bold green)"
error_symbol = "[->](bold red)"
vimcmd_symbol = "[<-](bold green)"
vimcmd_replace_one_symbol = "[<-](bold purple)"
vimcmd_replace_symbol = "[<-](bold purple)"
vimcmd_visual_symbol = "[<-](bold yellow)"

[directory]
truncate_to_repo = false
style = "bold blue"

[hostname]
ssh_only = true
ssh_symbol = ""
style = "bold green"
format = '@[$ssh_symbol$hostname]($style) in '

[username]
style_user = "bold yellow"
format = '[$user]($style)'

[gcloud]
disabled = true

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[git_metrics]
disabled = true

[git_status]
disabled = true

[docker_context]
disabled = true

[jobs]
disabled = true

[hg_branch]
disabled = false
