# espanso match file
# For a complete introduction, visit the official docs at: https://espanso.org/docs/
imports:
  - private.yml
  - links.yml

matches:
  - trigger: ":td"
    replace: "{{today}}"
    vars:
      - name: today
        type: date
        params:
          format: "%Y/%m/%d"
  - trigger: ":sig"
    replace: |
      Best regards,
      Max
