#!/usr/bin/env sh
# shellcheck disable=all

# bind cmd+m to noop
cmd - m : true

# alt - p : yabai -m window --focus stack.prev
# alt - n : yabai -m window --focus stack.next || yabai -m window --focus stack.first

# 0x32 = backtick
cmd - 0x32 : ~/.config/yabai/toggle_space.sh 1
cmd - escape : ~/.config/yabai/focus_space.sh recent

ctrl + shift - h : yabai -m window --focus west || ~/.config/yabai/restore_window_focus.sh || ~/.config/yabai/focus_display.sh west
ctrl + shift - j : yabai -m window --focus south || ~/.config/yabai/restore_window_focus.sh || ~/.config/yabai/focus_display.sh south
ctrl + shift - k : yabai -m window --focus north || ~/.config/yabai/restore_window_focus.sh || ~/.config/yabai/focus_display.sh north
ctrl + shift - l : yabai -m window --focus east || ~/.config/yabai/restore_window_focus.sh || ~/.config/yabai/focus_display.sh east

# swap
alt + shift - h : ~/.config/yabai/swap_and_focus.sh west
alt + shift - j : ~/.config/yabai/swap_and_focus.sh south
alt + shift - k : ~/.config/yabai/swap_and_focus.sh north
alt + shift - l : ~/.config/yabai/swap_and_focus.sh east

# resize
cmd + shift - h : yabai -m window west --resize right:-50:0 || yabai -m window --resize right:-50:0
cmd + shift - k : yabai -m window north --resize bottom:0:50 || yabai -m window --resize bottom:0:50
cmd + shift - j : yabai -m window south --resize top:0:-50 || yabai -m window --resize top:0:-50
cmd + shift - l : yabai -m window east --resize left:50:0 || yabai -m window --resize left:50:0

# move to space
alt + shift - 1 : yabai -m window --space 1; ~/.config/yabai/focus_space.sh 1
alt + shift - 2 : yabai -m window --space 2; ~/.config/yabai/focus_space.sh 2
alt + shift - 3 : yabai -m window --space 3; ~/.config/yabai/focus_space.sh 3
alt + shift - 4 : yabai -m window --space 4; ~/.config/yabai/focus_space.sh 4
alt + shift - 5 : yabai -m window --space 5; ~/.config/yabai/focus_space.sh 5
alt + shift - 6 : yabai -m window --space 6; ~/.config/yabai/focus_space.sh 6
alt + shift - 7 : yabai -m window --space 7; ~/.config/yabai/focus_space.sh 7
alt + shift - 8 : yabai -m window --space 8; ~/.config/yabai/focus_space.sh 8
alt + shift - 9 : yabai -m window --space 9; ~/.config/yabai/focus_space.sh 9
alt + shift - 0 : yabai -m window --space 10; ~/.config/yabai/focus_space.sh 10
alt + shift - n : yabai -m window --space next; ~/.config/yabai/focus_space.sh next
alt + shift - p : yabai -m window --space prev; ~/.config/yabai/focus_space.sh prev
