[user]
name = "madmaxieee"
email = "76544194+madmaxieee@users.noreply.github.com"

[ui]
conflict-marker-style = "git"
default-command = "log"
diff-editor = ":builtin"
diff-formatter = ":git"
pager = "delta"

[aliases]
d = ["diff"]
e = ["edit"]
fa = ["git", "fetch", "--all-remotes"]
llog = ["log", "-T", "builtin_log_detailed"]
rb = ["rebase"]
w = ["workspace"]

[working-copy]
eol-conversion = "none"
