[ui]
default-command = "log"
diff-formatter = ":git"
pager = "delta"
conflict-marker-style = "git"

[aliases]
e = ["edit"]
rb = ["rebase"]
llog = ["log", "-T", "builtin_log_detailed"]

[working-copy]
eol-conversion = "none"

[user]
name = "madmaxieee"
email = "76544194+madmaxieee@users.noreply.github.com"
